# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_photo',
            field=models.ImageField(upload_to='userphoto/'),
        ),
    ]
