# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171101_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='second_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
